---
title: "decoupleR"
author: "Dustin Schilling"
date: "9 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(decoupleR)
library(readr)
library(readxl)
library(dplyr)
library(tibble)
library(tidyr)
```

## Input Data

```{r}
# network combined
combined_metab_gene_hallmarks <- read_csv("../support/combined_metab_gene_hallmarks.csv")
network_combined <- combined_metab_gene_hallmarks
network_combined$mor <- 1
network_combined$term <- gsub("HALLMARK_","", network_combined$term)
network_combined$term <- gsub("_", " ", network_combined$term)

# network separated
network_met <- network_combined[which(grepl("HMDB", network_combined$feature) == T),]
network_prot <- network_combined[which(grepl("HMDB", network_combined$feature) == F),]


# combine and separated matrix as input for pathway
metabolomics_DE_t <- readRDS("../results/metabolomics_DE_t.Rda")
proteomics_DE_t <- readRDS("../results/proteomics_DE_t.Rda")



# combine
```

# Pathway enrichment analysis
```{r}

```

# Single patient pathway enrichment analysis